apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leader-election-cluster
  labels:
    app: leader-eelction-app
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["*"]
    