apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leader-election-role
  namespace: leader-election-test
  labels:
    app: leader-election-app
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["*"]
